Description: >
  Vuong Xuan Vo / Capstone Project
  Creates an Amazon EKS Cluster

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: capstone-project
    Type: String

Resources:
  EKSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-cluster-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Version: "1.19"
      Name: !Sub ${EnvironmentName}-cluster
      RoleArn: !GetAtt EKSIAMRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${EnvironmentName}-ControlPlaneSecurityGroup
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: ${EnvironmentName}-SubnetIds

Outputs:
  EksId:
    Description: EKS id
    Value: !Ref EKSCluster
    Export:
      Name: !Sub ${EnvironmentName}-EKSCluster

  EKSIAMRole:
    Description: Role for accessing and creating aws resources
    Value: !GetAtt EKSIAMRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EKSRole
