Description: >
  Vuong Xuan Vo / Capstone Project
  Creates two individual hosts to manage the EKS-Cluster

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: capstone-project
    Type: String
  SSHKeyName:
    Description: SSH key for management access
    Default: udacity
    Type: String
  amiImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-005de95e8ff495156
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-management-SG
      GroupDescription: Allow port 22 for management
      VpcId:
        Fn::ImportValue:
          Fn::Sub: ${EnvironmentName}-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  managementHost1:
    Type: AWS::EC2::Instance
    DependsOn: InstanceSecurityGroup
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      NetworkInterfaces:
        - DeviceIndex: 0
          GroupSet: 
            - Ref: "InstanceSecurityGroup"
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${EnvironmentName}-PUB1-SN"
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management1
        - Key: Project
          Value: !Ref EnvironmentName

  managementHost2:
    Type: AWS::EC2::Instance
    DependsOn: InstanceSecurityGroup
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      NetworkInterfaces:
        - DeviceIndex: 0
          GroupSet: 
            - Ref: "InstanceSecurityGroup"
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${EnvironmentName}-PUB2-SN"
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management2
        - Key: Project
          Value: !Ref EnvironmentName

  managementHostEIP1:
    Type: AWS::EC2::EIP
    Properties:
        InstanceId: !Ref managementHost1
        Tags:
        - Key: Name
          Value: !Sub Elastic IP for our ${EnvironmentName}-management1

  managementHostEIP2:
    Type: AWS::EC2::EIP
    Properties:
        InstanceId: !Ref managementHost2
        Tags:
        - Key: Name
          Value: !Sub Elastic IP for our ${EnvironmentName}-management2