apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: capstone-project-frontend-deployment
  labels:
    app: capstone-project-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project-frontend-app
  template:
    metadata:
      labels:
        app: capstone-project-frontend-app
    spec:
      volumes:
        - name: globoticket-app-config-volume
          configMap:
            name: globoticket-app-config
      containers:
        - name: capstone-project-frontend-app
          image: vuongvx/globoticket-app
          ports:
            - containerPort: 80
          volumeMounts:
            - name: globoticket-app-config-volume
              mountPath: /usr/share/nginx/html/appsettings.json
              subPath: appsettings.json
