---
- name: "Download kubectl"
  get_url:
    url: https://s3.us-west-2.amazonaws.com/amazon-eks/1.19.6/2021-01-05/bin/linux/amd64/kubectl
    dest: $HOME/kubectl
    checksum: sha256:https://s3.us-west-2.amazonaws.com/amazon-eks/1.19.6/2021-01-05/bin/linux/amd64/kubectl.sha256
    mode: 0700
    timeout: 120
    use_proxy: no
    validate_certs: false
    force: no

- name: "Apply execute permissions to the binary"
  file:
    path: $HOME/kubectl
    mode: u+rwx,g=,o=
    state: file

- name: Creates directory
  file:
    path: $HOME/bin
    state: directory

- name: "Copy the binary to a folder to the $PATH"
  copy:
    src: $HOME/kubectl
    dest: $HOME/bin  
    mode: u+rwx,g=,o=
    remote_src: true

- name: "Export PATH"
  shell: export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "Add the $HOME/bin path to the shell initialization file"
  shell: echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
    chdir: $HOME
