- name: Copy backend service configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-backend-service.yaml"
    dest: $HOME

- name: Copy frontend service configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-frontend-service.yaml"
    dest: $HOME

- name: Create backend service configuration
  command: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-backend-service.yaml"
  args:
    chdir: $HOME

- name: Create frontend service configuration
  command: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-frontend-service.yaml"
  args:
    chdir: $HOME
