---
- name: "Configure the EKS cluster with kubectl"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  pre_tasks:
    - name: ensure python3 is installed
      become: yes
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present

    - name: install kubernetes pip package
      pip:
        name: kubernetes
        state: present

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: globoticket
        api_version: v1
        kind: Namespace
        state: present
  roles:
    - capstone-deployment
    - capstone-service
